common:
  project: Lipsiablog
  email_from: info@lipsiasoft.com
  email_help: help@lipsiasoft.com
  host_addr: http://www.lipsiablog.com

production:
  host_addr: http://www.lipsiablog.com

development:
  host_addr: http://localhost:3000
  
test:
  host_addr: http://localhost:3000